const express = require('express')
require('dotenv').config()
const userRoute=require('./routes/Users')
const expensesRoute=require('./routes/Expenses')
const connection = require('./dbConfig/connection')
connection()
const app = express()
const cors = require('cors')
app.use(express.json())
app.use(cors())
app.use(userRoute)
app.use(expensesRoute)
app.listen(process.env.PORT, () => {
    console.log(`Example app listening on port ${process.env.PORT}`)
  })